changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: ✨ Features
      labels:
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - fix
    - title: ⚡️ Performance Improvements
      labels:
        - perf
    - title: ⚠️ Deprecations
      labels:
        - deprecate
    - title: ↩️ Reverts
      labels:
        - revert
    - title: 📦 Dependencies
      labels:
        - deps
    - title: 📝 Documentation
      labels:
        - docs
    - title: ♻️ Code Refactoring
      labels:
        - refactor
